language: java
before_install:
  # Install ia32-libs
  # From https://github.com/JakeWharton/ActionBarSherlock/blob/dev/.travis.yml
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  
  # Install PhantomJS 1.9.1
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-1.9.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.9.1-linux-x86_64 /usr/local/phantomjs
  
before_script:
  - phantomjs --version
  - phantomjs --webdriver=9134 2>&- 1>&- &
  
install: mvn install -DskipTests=true -Pupdate-thirdparties -B
script: mvn verify -Dminium.remote.url=http://localhost:9134
