language: java
before_install:
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-1.9.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.9.1-linux-x86_64 /usr/local/phantomjs
before_script:
  - phantomjs --version
  - phantomjs --webdriver=9134 &
script: mvn test -Dminium.remote.url=http://localhost:9134
